# Generated by Django 2.0.2 on 2018-05-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iirs',
            new_name='Iris',
        ),
    ]
