# Generated by Django 2.0.2 on 2018-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_auto_20180508_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='classified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
