# Generated by Django 2.0.2 on 2018-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20180509_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='classified',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
