# Generated by Django 2.0.2 on 2018-05-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0005_auto_20180509_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
