# Generated by Django 2.0.5 on 2018-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0006_iris_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='clf_hash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
