# Generated by Django 2.0.5 on 2018-05-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0007_iris_clf_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iris',
            name='clf_hash',
        ),
    ]
